version: "2"
services:
  papi:
    build: ./
    labels:
      - "traefik.backend=papi"
      - "traefik.frontend.rule=Host:papi.docker.localhost"
    environment:
      - APACHE_SERVER_NAME=papi.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - SESSION_LIFETIME=43200
      - SESSION_KEY=b...e
      # comma seperated whitelist
      - CORS_WHITELIST=rapp.docker.localhost
    networks:
      - default
    volumes:
      # Dev only map, do not map for production, copy in Dockerfile to sandbox
      - ./:/app
networks:
  default:
    external:
      name: docker_docker-localhost
